/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ClrgODRSzuu
 */
import { Input } from "@/components/ui/input";
import {
  CardContent,
  CardFooter,
  Card,
  CardHeader,
} from "@/components/ui/card";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { JSX, SVGProps } from "react";
import Image from "next/image";

export function HomeUI() {
  return (
    <div
      key="1"
      className="grid md:grid-cols-2 gap-8 lg:gap-12 xl:gap-16 items-start px-4 pb-4"
    >
      <div className="space-y-4">
        <h1 className="text-3xl font-bold">Upcoming Shows</h1>
        <div className="flex items-center space-x-2">
          <div className="relative w-full">
            <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
            <Input
              className="pl-8 w-full"
              placeholder="Search for events"
              type="search"
            />
          </div>
        </div>
        <div className="grid gap-4">
          <Card>
            <div className="p-4">
              <div className="text-sm font-medium uppercase text-gray-500 dark:text-gray-400">
                Upcoming
              </div>
              <h2 className="text-xl font-bold leading-none mt-1">
                Summer Music Festival
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Artist: John Doe
              </p>
            </div>
            <CardContent className="p-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <CalendarIcon className="w-4 h-4" />
                    <span>July 19, 2023</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <ClockIcon className="w-4 h-4" />
                    <span>6:00 PM - 11:00 PM</span>
                  </div>
                </div>
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <MapPinIcon className="w-4 h-4" />
                    <span>Central Park</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <DollarSignIcon className="w-4 h-4" />
                    <span>$25 - $100</span>
                  </div>
                </div>
              </div>
            </CardContent>
            <div className="border-t border-gray-100 dark:border-gray-800">
              <CardFooter className="p-4 flex justify-end">
                <Link
                  className="font-medium underline underline-offset-2"
                  href="#"
                >
                  View Details
                </Link>
              </CardFooter>
            </div>
          </Card>
          <Card>
            <div className="p-4">
              <div className="text-sm font-medium uppercase text-gray-500 dark:text-gray-400">
                Upcoming
              </div>
              <h2 className="text-xl font-bold leading-none mt-1">
                Jazz in the Park
              </h2>
            </div>
            <CardContent className="p-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <CalendarIcon className="w-4 h-4" />
                    <span>August 5, 2023</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <ClockIcon className="w-4 h-4" />
                    <span>7:00 PM - 10:00 PM</span>
                  </div>
                </div>
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <MapPinIcon className="w-4 h-4" />
                    <span>Elmwood Park</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <DollarSignIcon className="w-4 h-4" />
                    <span>Free</span>
                  </div>
                </div>
              </div>
            </CardContent>
            <div className="border-t border-gray-100 dark:border-gray-800">
              <CardFooter className="p-4 flex justify-end">
                <Link
                  className="font-medium underline underline-offset-2"
                  href="#"
                >
                  View Details
                </Link>
              </CardFooter>
            </div>
          </Card>
          <Card>
            <div className="p-4">
              <div className="text-sm font-medium uppercase text-gray-500 dark:text-gray-400">
                Upcoming
              </div>
              <h2 className="text-xl font-bold leading-none mt-1">
                Rock the City: Benefit Concert
              </h2>
            </div>
            <CardContent className="p-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <CalendarIcon className="w-4 h-4" />
                    <span>August 22, 2023</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <ClockIcon className="w-4 h-4" />
                    <span>5:00 PM - 11:00 PM</span>
                  </div>
                </div>
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <MapPinIcon className="w-4 h-4" />
                    <span>City Hall Plaza</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <DollarSignIcon className="w-4 h-4" />
                    <span>$50 - $250</span>
                  </div>
                </div>
              </div>
            </CardContent>
            <div className="border-t border-gray-100 dark:border-gray-800">
              <CardFooter className="p-4 flex justify-end">
                <Link
                  className="font-medium underline underline-offset-2"
                  href="#"
                >
                  View Details
                </Link>
              </CardFooter>
            </div>
          </Card>
        </div>
      </div>
      <div className="space-y-4">
        <Card>
          <div className="p-4 space-y-4">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold">Summer Music Festival</h1>
              <div className="text-sm font-medium uppercase text-gray-500 dark:text-gray-400">
                Upcoming
              </div>
              <div className="text-lg font-bold">Artist: John Doe</div>
            </div>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div className="space-y-1">
                <div className="flex items-center space-x-2">
                  <CalendarIcon className="w-4 h-4" />
                  <span>July 19, 2023</span>
                </div>
                <div className="flex items-center space-x-2">
                  <ClockIcon className="w-4 h-4" />
                  <span>6:00 PM - 11:00 PM</span>
                </div>
              </div>
              <div className="space-y-1">
                <div className="flex items-center space-x-2">
                  <MapPinIcon className="w-4 h-4" />
                  <span>Central Park</span>
                </div>
                <div className="flex items-center space-x-2">
                  <DollarSignIcon className="w-4 h-4" />
                  <span>$25 - $100</span>
                </div>
              </div>
            </div>
          </div>
          <CardContent className="p-4">
            <Image
              alt="Concert"
              className="aspect-video overflow-hidden rounded-lg object-cover"
              height="300"
              src="/placeholder.svg"
              width="600"
            />
          </CardContent>
          <div className="border-t border-gray-100 dark:border-gray-800">
            <CardFooter className="p-4 flex justify-end">
              <Button variant="outline">Add to Calendar</Button>
            </CardFooter>
          </div>
        </Card>
        <Card>
          <CardHeader className="p-4">
            <h1 className="text-2xl font-bold">Description</h1>
          </CardHeader>
          <CardContent className="p-4">
            <p>
              The Summer Music Festival is an annual event that brings together
              the best music, food, and fun. Join us for a day of amazing
              performances by top artists. Whether you love pop, rock, or
              hip-hop, you&#39;ll find something to groove to at the Summer
              Music Festival. In addition to the great music, there will be
              plenty of delicious food and refreshing drinks available. So come
              on down and enjoy the music!
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function SearchIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function CalendarIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  );
}

function ClockIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}

function MapPinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  );
}

function DollarSignIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  );
}
